# Generated by Django 5.2.1 on 2025-07-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_urls',
            field=models.ImageField(null=True, upload_to='posts/images'),
        ),
    ]
